theme: jekyll-theme-merlot
title: Shawn Dominguez Development
description: Welcome to a quick overview of my experience in application development and programming. Feel free to bookmark this page to stay up to date with any projects I am working on!
